Bug#39688586 Compile issue in NDB with gcc 16.1
storage/ndb/src/common/util/testSecureSocket.cpp: In constructor ‘EchoSession::EchoSession(NdbSocket&&, bool, SSL_CTX*)’:
storage/ndb/src/common/util/testSecureSocket.cpp:173:37: error: ‘<unknown>’ may be used uninitialized [-Werror=maybe-uninitialized]
  173 |         m_secure_socket(std::move(s)) {}
      |                                     ^
In file included from storage/ndb/src/common/util/testSecureSocket.cpp:44:
storage/ndb/include/util/SocketServer.hpp:57:5: note: by argument 2 of type ‘const NdbSocket&’ to ‘SocketServer::Session::Session(const NdbSocket&)’ declared here
   57 |     Session(const NdbSocket &sock)
      |     ^~~~~~~

Removed unused NdbSocket from ServerSocket::Session.

Change-Id: I0c10247e1cde21025f1b73a11e4aebd36bb160f5