Bug#39619826 False restrict warning breaks build with GNU C++ 12
Problem:

Build failed with MYSQL_MAINTAINER_MODE=ON and GNU C++ 12.2.1.

    /usr/include/c++/12/bits/char_traits.h:431:56: error: 'void* __builtin_memcpy(void*, const void*, long unsigned int)' accessing 9223372036854775810 or more bytes at offsets -4611686018427387902 and [-4611686018427387903, 4611686018427387904] may overlap up to 9223372036854775813 bytes at offset -3 [-Werror=restrict]
        431 |         return static_cast<char_type*>(__builtin_memcpy(__s1, __s2, __n));
            |                                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~

Fix:

Disable warning Wrestrict when building with GNU C++ 12.1 to 12.3 as a
workaround for GNU C++ bug 105651, see
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105651 .

Change-Id: I4dcceebe477d919d5b7b2ad586559243338f2523